#!/usr/bin/env python3
"""Cycle-7 persistence: backlog + state. Committed as it ran."""
import json, os, time

R = '/opt/targets/aphorism-cli/.swarm/'
CYCLE = 7

W8_NOTE = (
    " [CYCLE 7 DONE] Builder produced tools/mutation-matrix-final.json (generated by the instrument at"
    " --rev d8403a35 --json, never hand-edited), tools/detection-floor.mjs (the published comparison"
    " finding), and registered it as slot [6/6] in tools/run-all.mjs. RULING W8-R1, printed on every run"
    " including failing ones: a mutation SKIPPED at HEAD because its anchor occurs 0 times is NOT detection"
    " lost -- it is a RETIRED CLAIM in its own always-listed bucket -- with the case AGAINST recorded"
    " (anchor-count-0 is a mechanical proxy; a REWORDED claim would evade it), the falsifier named"
    " (guard-inventory.mjs at HEAD is the adjudicator for reworded-but-unguarded claims), and a scope guard"
    " failing any skip whose reason is not anchor-count-0 as SKIP-UNPROVEN. Partition at HEAD: 14 same-guard,"
    " 1 guard-changed (M08, named on both sides), 3 claim-gone (M01-M03), 0 detection lost. Conductor gate"
    " 13/13: C3 RE-DERIVED the artifact independently (own --rev HEAD --json run, 0 verdict differences, 0"
    " guardTitle differences, identical skippedClaims, identity control GREEN both sides) so the artifact is"
    " not fabricated; C4' recomputed the whole partition from firedGuards and required set-for-set agreement;"
    " C5/C5b are conductor injections on ids the builder did not use (M09 CAUGHT->SILENT, M15 deleted from"
    " both arrays), both correctly failed and named; C6 is the green control on the same path; C7 proved the"
    " FRESH-BY-CONTENT exemption cannot wave through a genuinely stale record (measuredCommit -> e40736c,"
    " whose diff touches tools/mutation-matrix.mjs: exit 3 STALE, no partition printed). NOTE the builder"
    " WIDENED the freshness check on its own initiative: an exact-sha mismatch is exempted as FRESH-BY-CONTENT"
    " when the diff to HEAD touches none of README.md/docs/src/bin/test/.github/tools/mutation-matrix.mjs."
    " C2b' verified that path set is a superset of the real verdict inputs (mutations edit only README.md and"
    " src/corpus.js; guards fire from test/; the 18-row mutation table is hardcoded in the instrument and NOT"
    " re-derived from guard-inventory.mjs at runtime), so the exemption is sound -- but it is a self-granted"
    " widening and is recorded as such rather than absorbed."
)

W6_NOTE = (
    " [CYCLE 7 HELD] corpus sha256 77a4de5c and --help sha256 d759d781 both re-measured, unmoved."
    " git status --porcelain over src bin test .github README.md docs EMPTY. Dependency clause per the cycle-6"
    " restatement: 0 manifests/lockfiles tracked, 0 on disk, no node_modules, 24 tools/ imports all node:"
    " builtins, converse control rejecting 'lodash', a relative import and a node_modules path 3/3. Suite green"
    " 128 tests / 128 pass / 0 fail / 0 skipped. The single citation window S-8 permits was spent in cycle 4;"
    " no commit since has opened another, and this cycle's commit does not."
)

b = json.load(open(R + 'backlog.json'))
for i in b['items']:
    if i['id'] == 'W-8':
        i['status'] = 'done'
        i['updated_cycle'] = CYCLE
        i['notes'] = i['notes'] + W8_NOTE
    if i['id'] == 'W-6':
        i['notes'] = i['notes'] + W6_NOTE
json.dump(b, open(R + 'backlog.json.tmp', 'w'), indent=1)
os.replace(R + 'backlog.json.tmp', R + 'backlog.json')

s = json.load(open(R + 'state.json'))
s['cycle'] = CYCLE
s['counters']['k_current'] = 5
s['counters']['wave_streak'] = 0
s['counters']['consecutive_no_value'] = 0
s['counters']['window_tokens_attributed'] = 13660922
s['last_cycle'] = {
    'cycle': CYCLE,
    'work': 'build-wave (1 direct Agent call, headless fallback: W-8 on fable, the sole unblocked must-have)',
    'outcome': ('value -- W-8 verified done, 13/13 gate cells pass. Three of the thirteen had to be re-taken in'
                ' an addendum: all three failures were the conductor own instrument, none of them the work'
                ' (D-R8-19). Clean wave: 0 reverts, 0 failed verifies. W-10, the last open must-have, is now'
                ' unblocked.'),
    'ts': time.strftime('%Y-%m-%dT%H:%M:%S.000Z', time.gmtime()),
}
json.dump(s, open(R + 'state.json.tmp', 'w'), indent=2)
os.replace(R + 'state.json.tmp', R + 'state.json')

from collections import Counter
print(Counter(i['status'] for i in b['items']))
print('cycle', s['cycle'], 'k_current', s['counters']['k_current'], 'streak', s['counters']['wave_streak'])
